---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: javawebapp
  name: java-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: expresscart1
    spec:
      containers:
      - image: saikrishna01/expresscart1:latest
        name: javawebapp
        ports:
        - name: javawebapp
          containerPort: 8080  
---
# Node Port Service
apiVersion: v1
kind: Service
metadata:
  labels:
    name: expresscart1
  name: expresscart1
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    name: expresscart1
